payments_app/payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'
urlpatterns = [
    # /payments/
    path('', views.listAllPayments, name='allPayments'),
    path('payment/<payment_id>/', views.showPayment, name='showPayment'),
    path('newPayment/', views.newPayment, name='newPayment'),
    path('deletePayment/<payment_id>/', views.deletePayment, name='deletePayment'),
    path('settlePayment/<payment_id>/', views.settlePayment, name='settlePayment'),
    path('filterPayments/', views.filterPayments, name='filterPayments'),

    # Views that render a GUI
    path('allPayments/', views.listAllPaymentsGUI, name='allPaymentsGUI'),
    path('paymentGUI/<payment_id>/', views.showPaymentGUI, name='showPaymentGUI'),
    path('newPaymentGUI/', views.newPaymentGUI, name='newPaymentGUI'),
    path('processPayment/', views.processPayment, name='processPayment'),
    path('deletePaymentGUI/<payment_id>/', views.deletePaymentGUI, name='deletePaymentGUI'),
    path('settlePaymentGUI/<payment_id>/', views.settlePaymentGUI, name='settlePaymentGUI'),
    path('filterPaymentGUI/', views.filterPaymentsGUI, name='filterPaymentsGUI'),
]

payments_app/payments_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/api/payments/allPayments', permanent=True)),
    path('api/payments/', include('payments.urls')),
    path('admin/', admin.site.urls),
]

payments_app/payments/models.py
from django import forms
from django.db import models
from django.forms import ModelForm
import uuid

class Base(models.Model):
    CC = "credit_card"
    MBWay = "mbway"
    
    SUCCESS = "success"
    ERROR = "error"
    SETTLED = "settled"

    pay_method = (
        (CC, 'credit_card'),
        (MBWay, 'mbway')
    )
    statusOP = (
        (SUCCESS, 'success'),
        (ERROR, 'error'),
        (SETTLED, 'settled')
    )

    payment_id = models.UUIDField(max_length=200, primary_key=True, default=uuid.uuid4)     # primary key, auto generated UUID
    amount = models.FloatField()                
    payment_method = models.CharField(max_length=50, default=CC, choices=pay_method)
    created_at = models.DateTimeField(auto_now_add=True)          
    status = models.CharField(max_length=20, choices=statusOP)
    settled_at = models.DateTimeField(null=True, blank=True)             
    settled_amount = models.FloatField(null=True, blank=True, default=0)
    def __str__(self):
        baseStr = "Payment ID: " + str(self.payment_id) + ", Amount: " + str(self.amount) + "€, Method: " + self.payment_method + ", Created at: " + str(self.created_at) + ", Status: " + self.status 
        if self.settled_at != None:
            return baseStr + ", Settled at: " + str(self.settled_at) + ", Settled amount: " + str(self.settled_amount) + "€"
        else:
            return baseStr

class CreditCard(models.Model):
    payment_id = models.OneToOneField(Base, on_delete=models.CASCADE)  # Foreign key to Base
    number = models.CharField(max_length=16)                                     
    name = models.CharField(max_length=30)                             
    expiration_month = models.CharField(max_length=2)   
    expiration_year = models.CharField(max_length=4)  
    cvv = models.CharField(max_length=3)
    def __str__(self):
        return str(self.payment_id) + ", Card Number: " + self.number + ", Name: " + self.name + ", Exp. Month: " + self.expiration_month + ", Exp. Year: " + self.expiration_year + ", CVV: " + self.cvv + "\n"
        
class MbWay(models.Model):
    payment_id = models.OneToOneField(Base, on_delete=models.CASCADE)  # Foreign key to base
    phone_number = models.CharField(max_length=9)
    def __str__(self):
        return str(self.payment_id) + ", Phone Number: " + self.phone_number + "\n"

class BaseForm(ModelForm):
    class Meta:
        model = Base
        fields = ('payment_id', 'amount', 'payment_method', 'status', 'settled_at', 'settled_amount')
        widgets = {
            'payment_id': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control', 'min': 0}),
            'payment_method': forms.Select(attrs={'class': 'form-control'}, choices=Base.pay_method),
            'settled_at': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'date'}),
            'settled_amount': forms.NumberInput(attrs={'class': 'form-control', 'min': 0, 'default': 0}),
            'status': forms.HiddenInput(attrs={'class': 'form-control', 'default': Base.ERROR}),
        }

class CreditCardForm(ModelForm):
    class Meta:
        model = CreditCard
        fields = '__all__'
        widgets = {
            'payment_id': forms.TextInput(attrs={'readonly': 'readonly'}),
            'number': forms.NumberInput(attrs={'class': 'form-control', 'min': 1111111111111111, 'placeholder': 1111111111111111}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'John Doe'}),
            'expiration_month': forms.NumberInput(attrs={'class': 'form-control', 'max': 12, 'min': 1}),
            'expiration_year': forms.NumberInput(attrs={'class': 'form-control', 'min': 2021}),
            'cvv': forms.NumberInput(attrs={'class': 'form-control', 'max': 999}),
        }

class MbWayForm(ModelForm):
    class Meta:
        model = MbWay
        fields = '__all__'
        widgets = {
            'payment_id': forms.TextInput(attrs={'readonly': 'readonly'}),
            'phone_number': forms.NumberInput(attrs={'class': 'form-control', 'maxlength': 9, 'placeholder': 910000000})
        }

payments_app/payments/views.py
from django.forms.models import model_to_dict
from django.http.request import HttpRequest
from django.http.response import HttpResponse, HttpResponseBadRequest, HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from .models import Base, CreditCard, MbWay, BaseForm, CreditCardForm, MbWayForm
from kafka import KafkaProducer
import pickle

from django.views.decorators.csrf import csrf_exempt
import datetime

# Refunds microservice url (only used in GUI version to redirect to newRefund page)
refunds_url = 'http://172.26.1.2:2222/api/refunds/'

# Kafka URL
kafka_server = 'kafka:9092'

def kafkaProd(topic, key, data):
    producer = KafkaProducer(bootstrap_servers=kafka_server)
    serialized_data = pickle.dumps({'data': data}, pickle.HIGHEST_PROTOCOL)
    try:
        producer.send(topic, key=bytes(key,'utf-8'), value=serialized_data)
        producer.flush()
        return True
    except AssertionError:
        return False

#
# Auxiliar functions
#
def is_date(str):
    try:
        datetime.datetime.strptime(str, '%Y-%m-%d %H:%M')
        return True
    except ValueError:
        return False

def findPayment(payment_id):
    payment = get_object_or_404(Base, payment_id=payment_id)    
    # credit_card
    if payment.payment_method == Base.CC:   
        full_payment = CreditCard.objects.get(payment_id=payment_id)
    # MBWay
    else:                                   
        full_payment = MbWay.objects.get(payment_id=payment_id)
    return payment, full_payment

def is_valid_queryparam(param):
    return param != '' and param is not None

def filter(request):
    payments = Base.objects.all()
    payment_id = request.GET.get('payment_id')
    min_amount = request.GET.get('min_amount')
    max_amount = request.GET.get('max_amount')
    payment_method = request.GET.get('payment_method')
    status = request.GET.get('status')
    min_created_at = request.GET.get('min_created_at')
    max_created_at = request.GET.get('max_created_at')
    min_settled_at = request.GET.get('min_settled_at')
    max_settled_at = request.GET.get('max_settled_at')

    if is_valid_queryparam(payment_id) and payment_id != "Choose...":
        payments = payments.filter(payment_id=payment_id)

    if is_valid_queryparam(min_amount):
        payments = payments.filter(amount__gte=min_amount)

    if is_valid_queryparam(max_amount):
        payments = payments.filter(amount__lte=max_amount)

    if is_valid_queryparam(payment_method) and payment_method != "Choose...":
        payments = payments.filter(payment_method=payment_method)

    if is_valid_queryparam(status) and status != "Choose...":
        payments = payments.filter(status=status)

    if is_valid_queryparam(min_created_at):
        payments = payments.filter(created_at__gte=min_created_at)

    if is_valid_queryparam(max_created_at):
        payments = payments.filter(created_at__lt=max_created_at)

    if is_valid_queryparam(min_settled_at):
        payments = payments.filter(settled_at__gte=min_settled_at)

    if is_valid_queryparam(max_settled_at):
        payments = payments.filter(settled_at__lt=max_settled_at)

    return payments

def settlePayment_aux(payment_id):
    payment = get_object_or_404(Base, payment_id=payment_id)
    amount = payment.amount
    payment.settled_amount = amount
    payment.settled_at = datetime.datetime.now()
    payment.status = Base.SETTLED
    payment.save()

#
# Views that return Responses
# 
def listAllPayments(request):
    allPayments = []
    for p in Base.objects.all():
        refundDict = model_to_dict(p)
        refundDict['created_at'] = p.created_at
        allPayments.append(refundDict)
    return JsonResponse({'payments': allPayments}, status=200)

def showPayment(request, payment_id):
    payment, fullPayment = findPayment(payment_id)
    if payment == None:
        return HttpResponseNotFound('Payment not found')
    paymentDict = model_to_dict(payment)
    paymentDict['created_at'] = payment.created_at
    paymentDict['additional_parameters'] = model_to_dict(fullPayment)
    return JsonResponse({'base': paymentDict}, status=200)

def filterPayments(request):
    payments = [model_to_dict(p) for p in filter(request)]
    return JsonResponse({'filteredPayments': payments}, status=200)

@csrf_exempt
def newPayment(request):
    if request.method == 'POST':
        payment = Base()
        payment.amount = request.POST.get('amount')
        payment.payment_method = request.POST.get('payment_method')
        if 'settled_at' in request.POST:
            settled_at = request.POST.get('settled_at')
            if not is_date(settled_at):
                return HttpResponseBadRequest('"settled_at must have a format YYYY-MM-DD HH:MM"')
            else:
                payment.settled_at = request.POST.get('settled_at')
                payment.settled_amount = request.POST.get('settled_amount')
        payment.status = Base.SUCCESS
        if payment.settled_amount == payment.amount:
            payment.status = Base.SETTLED
        if payment.payment_method == Base.CC:
            cc = CreditCard()
            cc.payment_id = payment
            cc.number = request.POST.get('number')
            cc.name = request.POST.get('name')
            cc.expiration_month = request.POST.get('expiration_month')
            cc.expiration_year = request.POST.get('expiration_year')
            cc.cvv = request.POST.get('cvv')
            payment.save()
            cc.save()
        elif payment.payment_method == Base.MBWay:
            mbway = MbWay()
            mbway.payment_id = payment
            mbway.phone_number = request.POST.get('phone_number')
            payment.save()
            mbway.save()
        else:
            payment.status = Base.ERROR
            payment.save()
            return HttpResponseBadRequest('Bad payment method')
        
        paymentDict = model_to_dict(payment)
        paymentDict['created_at'] = payment.created_at
        if kafkaProd(topic='payment', key=str(payment.payment_id), data=paymentDict):
            return HttpResponse('New payment created.',status=200)
        else:
            payment.delete()
            return HttpResponse('Payment could not be published to topic.', status=503)
    return HttpResponseBadRequest("Data not found.")        

def settlePayment(request, payment_id):
    settlePayment_aux(payment_id)
    return HttpResponse('Payment settled.', status=200)

def deletePayment(request, payment_id):
    get_object_or_404(Base, payment_id=payment_id).delete()
    return HttpResponse('Payment ' + payment_id + ' deleted.', status=200)

#
# Views that render a GUI
#
def listAllPaymentsGUI(request):
    allPayments = Base.objects.all()
    return render(request, 'payments/allPayments.html', {'allPayments': allPayments})

def showPaymentGUI(request, payment_id):
    payment, full_payment = findPayment(payment_id)
    context = {
        'payment_id': payment_id, 
        'payment': full_payment, 
        'notSettled': payment.amount!=payment.settled_amount, 
        'refunds_url': refunds_url
    }
    return render(request, 'payments/showPayment.html', context)

def filterPaymentsGUI(request):
    return render(request, 'payments/filterPayments.html', {'payments': filter(request), 'payment_ids': list(Base.objects.all().values_list('payment_id', flat=True)), 'status': Base.statusOP, 'pay_method': Base.pay_method})

def newPaymentGUI(request):
    form = BaseForm(request.POST or None)
    payment_id = form['payment_id'].value()
    if form.is_valid():
        form.save()
        request.session['payment_id'] = payment_id
        request.session['payment_method'] = form['payment_method'].value()
        return redirect('payments:processPayment')
    return render(request, 'payments/createPayment.html', {'form': form})

def processPayment(request):
    payment_method = request.session['payment_method']
    payment_id = request.session['payment_id']
    basePayment = get_object_or_404(Base, payment_id=payment_id)
    # Only one payment method can be associated with a payment
    if not CreditCard.objects.filter(payment_id=payment_id) and not MbWay.objects.filter(payment_id=payment_id):
        if payment_method == Base.CC:
            form = CreditCardForm(request.POST or None, initial={'payment_id': payment_id})
        else:
            form = MbWayForm(request.POST or None, initial={'payment_id': payment_id})
        if form.is_valid():
            form.save()
            if float(basePayment.amount) == float(basePayment.settled_amount):
                basePayment.status = Base.SETTLED
            else:
                basePayment.status = Base.SUCCESS
            basePayment.save()
            paymentDict = model_to_dict(basePayment)
            paymentDict['created_at'] = basePayment.created_at
            kafkaProd(topic='payment', key=payment_id, data=paymentDict)
            return redirect('payments:allPaymentsGUI')
        return render(request, 'payments/processPayment.html', {'form': form, 'payment_method': payment_method})
    return HttpResponse("Only one payment method can be associated to a payment.")

def settlePaymentGUI(request, payment_id):
    settlePayment_aux(payment_id) 
    return redirect('payments:showPaymentGUI', payment_id)

def deletePaymentGUI(request, payment_id):
    get_object_or_404(Base, payment_id=payment_id).delete()
    return redirect('payments:allPaymentsGUI')

payments_app/payments/templates/payments/allPayments.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>All Payments</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body>
    
    <main role="main" class="container">
        <h3>All Payments</h3>
        
        {% if allPayments %}
            <ul>
                <hr />
            {% for payment in allPayments %}
                <li><a href="{% url 'payments:showPaymentGUI' payment.payment_id %}">{{ payment }}</a></li>
                <hr />
            {% endfor %}
            </ul>
        {% else %}
            <p>No payments are available.</p>
        {% endif %}
        
        <a href="{% url 'payments:newPaymentGUI' %}"><button type="button" class="btn btn-success" onclick="">New Payment</button></a>
        <a href="{% url 'payments:filterPaymentsGUI' %}"><button style="float: right;" type="button" class="btn btn-primary" onclick="">Filter Payments</button></a>    
  
    </main>
  </body>

payments_app/payments/templates/payments/createPayment.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>New Payment</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body>
    <main role="main" class="container">

    <h3>New Payment</h3>
    <hr />
    <form action="." method="post">  
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-12">
                <label for="id_payment_id">Payment ID</label>
                <input type="text" class="form-control" required id="id_payment_id" value="{{ form.payment_id.value }}" readonly='readonly' name="payment_id">
                <input type="hidden" class="form-control" id="initial-id_payment_id" value="{{ form.payment_id.value }}" name="initial-payment_id">
            </div>        
        </div>
        <div class="form-row">
            {% for field in form.visible_fields %}
            {% if field.label != 'Payment id' %}
                <div class="form-group col-md-4 col-lg-3">
                    <label for="id_amount">{{ field.label_tag }}</label>
                    {{ field }}</span>
                </div>
            {% endif %}
            {% endfor %}
        </div>
        <input type="hidden" name="status" value="error" id="id_status">
        <input type="submit" class="btn btn-success" value="Create Payment">
    </form>
    </main>

</body>

</html>

payments_app/payments/templates/payments/filterPayments.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Filter Payments</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body>
    <main role="main" class="container">
      <h3>Filter Payments</h3>
      <hr />
      <form method="GET" action=".">
        <div class="form-row">
            <div class="form-group col-12">
                <label for="payment_id">Payment ID</label>
                <select id="payment_id" class="form-control" name="payment_id">
                <option selected>Choose...</option>
                {% for p in payment_ids %}
                <option value="{{ p }}">{{ p }}</option>
                {% endfor %}
                </select>
            </div>        
        </div>
        <div class="form-row">
            <div class="form-group col-md-4 col-lg-3">
                <label for="status">Status</label>
                <select id="status" class="form-control" name="status">
                <option selected>Choose...</option>
                {% for st in status %}
                <option value="{{ st.0 }}">{{ st.0 }}</option>
                {% endfor %}
                </select>
            </div>
            <div class="form-group col-md-4 col-lg-3">
                <label for="payment_method">Payment Method</label>
                <select id="payment_method" class="form-control" name="payment_method">
                <option selected>Choose...</option>
                {% for p in pay_method %}
                <option value="{{ p.0 }}">{{ p.0 }}</option>
                {% endfor %}
                </select>
            </div>
            <div class="form-group col-md-4 col-lg-3">
                <label for="min_amount">Minimum Amount</label>
                <input type="number" min=0 class="form-control" id="min_amount" placeholder="0" name="min_amount">
            </div>
            <div class="form-group col-md-4 col-lg-3">
                <label for="max_amount">Maximum Amount</label>
                <input type="number" min=0 class="form-control" id="max_amount" placeholder="10000?" name="max_amount">
            </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-2 col-lg-3">
            <label for="min_created_at">Minimum creation date</label>
            <input type="date" class="form-control" id="min_created_at" name="min_created_at">
          </div>
          <div class="form-group col-md-2 col-lg-3">
            <label for="max_created_at">Maximum creation date</label>
            <input type="date" class="form-control" id="max_created_at" name="max_created_at">
          </div>
          <div class="form-group col-md-2 col-lg-3">
            <label for="min_settled_at">Minimum settle date</label>
            <input type="date" class="form-control" id="min_settled_at" name="min_settled_at">
          </div>
          <div class="form-group col-md-2 col-lg-3">
            <label for="max_settled_at">Maximum settle date</label>
            <input type="date" class="form-control" id="max_settled_at" name="max_settled_at">
          </div>
        </div>
        <a href="{% url 'payments:allPaymentsGUI' %}"><button type="button" class="btn btn-primary" onclick="">Back</button></a>
        <a href="{% url 'payments:filterPaymentsGUI' %}"><button style="float: right; margin-left: 1%;" type="button" class="btn btn-warning">Clear Filters</button></a>
        <button style="float: right;" type="submit" class="btn btn-success">Search</button>
    </form>
      <hr />

      <div class="row">
        <ul>
          {% for payment in payments %}
            <li>
                <a href="{% url 'payments:showPaymentGUI' payment.payment_id %}">{{ payment }}</a>
            </li>
            <hr />
          {% endfor %}
        </ul>
      </div>

    </main>

</body>

</html>

payments_app/payments/templates/payments/processPayment.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Continue Payment</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body>
    <main role="main" class="container">

    <h3>Continue Payment</h3>
    <hr />
    <form action="." method="post">  
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-12">
                <label for="id_payment_id">Payment ID</label>
                <input type="text" class="form-control" required id="id_payment_id" value="{{ form.payment_id.value }}" readonly='readonly' name="payment_id">
                <input type="hidden" class="form-control" id="initial-id_payment_id" value="{{ form.payment_id.value }}" name="initial-payment_id">
            </div>        
        </div>
        <div class="form-row">
            {% for field in form %}
            {% if field.label != 'Payment id' %}
                <div class="form-group col-md-4 col-lg-3">
                    <label for="id_amount">{{ field.label_tag }}</label>
                    {{ field }}</span>
                </div>
            {% endif %}
            {% endfor %}
        </div>
        <input type="submit" class="btn btn-success" value="Submit Payment">
    </form>
    </main>

</body>

</html>

payments_app/payments/templates/payments/showPayment.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Payment {{ payment_id }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body>
    
    <main role="main" class="container">
        <h3>Payment {{ payment_id }}</h3>
        <hr />

        <ul>
            <li>{{ payment }}</li>
        </ul>
        
        <hr />
        <a href="{% url 'payments:deletePaymentGUI' payment_id %}"><button class="btn btn-danger" type="button" >Delete Payment</button></a>
        <a href="{% url 'payments:allPaymentsGUI' %}"><button class="btn btn-primary" style="float: right;" type="button" >All Payments</button></a>
        
        {% if notSettled %}
            <a href="{% url 'payments:settlePaymentGUI' payment_id %}"><button class="btn btn-success" type="button" >Settle Payment</button></a>
        {% endif %}

        <a href="{{refunds_url}}newRefundGUI/{{payment_id}}"><button class="btn btn-primary" style="float: right; margin-right: 4px;" type="submit" >Ask for Refund</button>
        </a>
    </main>
  </body>