refunds_app/refunds/urls.py
from django.urls import path
from . import views

app_name = 'refunds'
urlpatterns = [
    # /refunds/
    path('', views.listAllRefunds, name='allRefunds'),
    path('setRefundTimeout/', views.setRefundTimeout, name='setRefundTimeout'),
    path('refund/<refund_id>/', views.showRefund, name='showRefund'),
    path('newRefund/<payment_id>', views.newRefund, name='newRefund'),
    path('filterRefunds/', views.filterRefunds, name='filterRefunds'),

    # Views that render a GUI
    path('allRefunds/', views.listAllRefundsGUI, name='allRefundsGUI'),
    path('refundGUI/<refund_id>/', views.showRefundGUI, name='showRefundGUI'),
    path('newRefundGUI/<payment_id>', views.newRefundGUI, name='newRefundGUI'),
    path('filterRefundsGUI/', views.filterRefundsGUI, name='filterRefundsGUI'),
]

refunds_app/refunds_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/api/refunds/allRefunds', permanent=True)),
    path('api/refunds/', include('refunds.urls')),
    path('admin/', admin.site.urls),
]

refunds_app/refunds/models.py
from django import forms
from django.db import models
from django.forms.models import ModelForm
import uuid


class Refund(models.Model):
    refund_id = models.UUIDField(max_length=200, primary_key=True, default=uuid.uuid4)
    payment_id = models.CharField(max_length=200, default='v')
    created_at = models.DateTimeField(auto_now_add=True)
    amount = models.FloatField()
    def __str__(self):
        return "Refund ID:" + str(self.refund_id) + ", Payment ID: " + str(self.payment_id) + ", Created at: " + str(self.created_at) + ", Amount: " + str(self.amount) + "€\n" 

class RefundForm(ModelForm):
    class Meta:
        model = Refund
        fields = '__all__'
        widgets = {
            'refund_id': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'payment_id': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control', 'min': 1, 'placeholder': 0}),
        }

refunds_app/refunds/views.py
from django.contrib import messages
from django.forms.models import model_to_dict
from django.http.response import HttpResponse, HttpResponseBadRequest, HttpResponseNotAllowed, HttpResponseServerError, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.csrf import csrf_exempt
from .models import Refund, RefundForm
from kafka import KafkaConsumer
import pickle
import datetime

# Payments microservice URL (only used in GUI version to redirect to showPayment page)
payments_url = 'http://172.26.1.1:1111/api/payments/'

# Kafka URL
kafka_server = 'kafka:9092'

# global variable
# Refunds can only be commited after refundTimeout minutes after receiving the request
refundTimeout = 30

def kafkaCon(topic, key):
    consumer = KafkaConsumer(topic, bootstrap_servers=[kafka_server], auto_offset_reset='earliest')
    for message in consumer:
        if message.key.decode('UTF-8') == key:
            return pickle.loads(message.value)['data']
    return None

#
# Auxiliar functions
#
def is_valid_queryparam(param):
    return param != '' and param is not None

def getTotalAmount(payment_id):
    refunds = Refund.objects.filter(payment_id=payment_id)
    amount = 0
    for refund in refunds:
        amount += refund.amount
    return amount

def refundTimePassed(initial_date):
    global refundTimeout
    date_now = datetime.datetime.now()
    delta = datetime.timedelta(minutes=refundTimeout)
    return date_now-delta > initial_date

def filter(request):
    refunds = Refund.objects.all()
    refund_id = request.GET.get('refund_id')
    payment_id = request.GET.get('payment_id')

    if is_valid_queryparam(refund_id) and refund_id != "Choose...":
        refunds = refunds.filter(refund_id=refund_id)
    
    if is_valid_queryparam(payment_id) and payment_id != "Choose...":
        refunds = refunds.filter(payment_id=payment_id)

    return refunds

def paymentToString(payment):
    return 'Payment ID: ' + str(payment['payment_id']) + ", Amount: " + str(payment['amount']) + "€, Method: " + payment['payment_method'] + ", Status: " + payment['status'] + ", Created at: " + payment['created_at'].strftime("%Y-%m-%d %H:%M:%S") + "\n" 

#
# Views that return Responses
#
def listAllRefunds(request):
    allRefunds = []
    for r in Refund.objects.all():
        refundDict = model_to_dict(r)
        refundDict['created_at'] = r.created_at
        allRefunds.append(refundDict)
    return JsonResponse({'refunds': allRefunds}, status=200)

@csrf_exempt
def setRefundTimeout(request):
    global refundTimeout
    t = request.POST.get('timeout')
    if is_valid_queryparam(t):
        refundTimeout = int(t)
        return HttpResponse('Refund timeout successfully set to ' + str(refundTimeout), status=200)
    return HttpResponseBadRequest('Invalid parameter input')

@csrf_exempt
def newRefund(request, payment_id):
    global refundTimeout
    start_date = datetime.datetime.now()
    refundAmount = float(request.POST.get('refund_amount'))
    payment = kafkaCon(topic='payment', key=payment_id)
    if payment != None:
        totalPaid = getTotalAmount(payment_id)
        remaining_amount = float(payment['amount'])-totalPaid
        if remaining_amount > 0:
            if refundTimePassed(start_date):
                return HttpResponseServerError('Could not process refund on time.')
            else:
                refundAmount = float(request.POST.get('refund_amount'))
                if refundAmount > remaining_amount:
                    return HttpResponseBadRequest('Refund amount must be less than or equal to ' + float(remaining_amount))  
                else:
                    refund = Refund()
                    refund.payment_id = payment_id
                    refund.amount = refundAmount
                    refund.save()
                    return HttpResponse('New refund created.', status=200)
        else:
            return HttpResponseNotAllowed('Payment with ID ' + str(payment_id) + " has been fully refunded already.")

def showRefund(request, refund_id):
    refund = get_object_or_404(Refund, refund_id=refund_id)
    payment = kafkaCon(topic='payment', key=refund.payment_id)
    if payment != None:
        refundDict = model_to_dict(refund)
        refundDict['created_at'] = refund.created_at
        return JsonResponse({'refund': refundDict, 'payment': payment}, status=200)      
    return HttpResponseServerError("Could not access payments service!")

def filterRefunds(request):
    refunds= [model_to_dict(r) for r in filter(request)]
    return JsonResponse({'filteredRefunds': refunds}, status=200)

#
# Views that render a GUI
#
def listAllRefundsGUI(request):
    global refundTimeout
    allRefunds = Refund.objects.all()
    t = request.GET.get('timeout')
    if is_valid_queryparam(t):
        refundTimeout = t
    return render(request, 'refunds/allRefunds.html', {'allRefunds': allRefunds, 'payments_url': payments_url, 'refundTimeout': refundTimeout})

def newRefundGUI(request, payment_id):
    global refundTimeout
    start_date = datetime.datetime.now()
    payment = kafkaCon(topic='payment', key=payment_id)

    if payment != None:
        totalPaid = getTotalAmount(payment_id)
        remaining_amount = float(payment['amount'])-totalPaid
        if remaining_amount > 0:
            form = RefundForm(request.POST or None)
            if form.is_valid() and not refundTimePassed(start_date):
                if float(form['amount'].value()) > remaining_amount:
                    messages.info(request, 'Cannot create a new refund with that amount. Max amount is: ' + str(remaining_amount))
                    return render(request, 'refunds/createRefund.html', {'form': form, 'payment_id': payment_id, 'remaining_amount': remaining_amount})  
                form.save()
                return redirect(payments_url+'paymentGUI/'+payment_id)
            return render(request, 'refunds/createRefund.html', {'form': form, 'payment_id': payment_id, 'remaining_amount': remaining_amount})
        else:
            return HttpResponseNotAllowed('Payment with ID ' + str(payment_id) + " has been fully refunded already.")

def filterRefundsGUI(request):
    all_refund_ids = list(Refund.objects.all().values_list('refund_id', flat=True))
    all_payment_ids = list(Refund.objects.all().values_list('payment_id', flat=True).distinct())
    return render(request, 'refunds/filterRefunds.html', {'refunds': filter(request), 'refund_ids': all_refund_ids, 'payment_ids': all_payment_ids})

def showRefundGUI(request, refund_id):
    refund = get_object_or_404(Refund, refund_id=refund_id)
    payment = kafkaCon(topic='payment', key=refund.payment_id)
    if payment != None:
        return render(request, 'refunds/showRefund.html', {'refund_id': refund_id, 'refund': refund, 'payment': paymentToString(payment)})      
    return HttpResponseServerError("Could not access payments service!")

refunds_app/refunds/templates/refunds/allRefunds.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>All Refunds</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body>
    
    <main role="main" class="container">
      <div class="form-row">
        <div class="form-group col-8">
          <h3>All Refunds</h3>
          {% if allRefunds %}
            <ul>
              <hr />
              {% for refund in allRefunds %}
                <li>
                  <b>Refund ID:</b><a href="{% url 'refunds:showRefundGUI' refund.refund_id %}"> {{ refund.refund_id }}</a>
                </li>
                <li>
                  <b>Amount:</b>{{ refund.amount }}</a>
                </li>
                <li>
                  <b>Associated Payment ID:</b><a href="{{payments_url}}paymentGUI/{{refund.payment_id}}"> {{ refund.payment_id }}</a>
                </li>
                <hr />
              {% endfor %}
            </ul>
          {% else %}
            <p>No refunds are available.</p>
            <hr />
          {% endif %}
          <a href="{% url 'refunds:filterRefundsGUI' %}"><button type="button" class="btn btn-primary" onclick="">Filter Refunds</button></a>    
        </div>
        <form method="GET" action=".">
          <div class="form-group col-lg-12">
            <label for="timeout"><h4>Refund Timeout</h4>(Currently at {{refundTimeout}} minutes)</label>
            <input type="text" class="form-control" required id="timeout" name="timeout" placeholder="Minutes...">
            <button type="submit" style="margin-top: 5px;" class="btn btn-success">Set Timeout</button>
          </div>       
        </form>
      </div>
    </main>
  </body>

refunds_app/refunds/templates/refunds/createRefund.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>New Refund</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body>
    <main role="main" class="container">

    <h3>New Refund</h3>
    <hr />
    <form action="{{payment_id}}" method="post">  
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-12">
                <label for="id_refund_id">Refund ID</label>
                <input type="text" class="form-control" required id="id_refund_id" value="{{ form.refund_id.value }}" readonly='readonly' name="refund_id">
                <input type="hidden" class="form-control" id="initial-id_refund_id" value="{{ form.refund_id.value }}" name="initial-refund_id">
            </div>        
        </div>
        
        <div class="form-row">
            <div class="form-group col-8">
                <label for="id_payment_id">Payment ID</label>
                <input type="text" class="form-control" required id="id_payment_id" value="{{ payment_id }}" readonly='readonly' name="payment_id">
            </div>     
            <div class="form-group col-4">
                <label for="">Amount that can be refunded</label>
                <input type="text" class="form-control" value="{{ remaining_amount }}" readonly='readonly' name="remaining_amount_id">
            </div>   
        </div>

        <div class="form-row">
            {% for field in form.visible_fields %}
            {% if field.label != 'Refund id' and field.label != 'Payment id' %}
                <div class="form-group col-md-4 col-lg-3">
                    <label for="id_amount">{{ field.label_tag }}</label>
                    {{ field }}</span>
                </div>
            {% endif %}
            {% endfor %}
        </div>
        <input type="submit" class="btn btn-success" value="Create Refund">
    </form>
    <hr/>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}    
    </main>
</body>

</html>

refunds_app/refunds/templates/refunds/filterRefunds.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Filter Refunds</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body>
    <main role="main" class="container">
      <h3>Filter Refunds</h3>
      <hr />
      <form method="GET" action=".">
        <div class="form-row">
          <div class="form-group col-12">
              <label for="refund_id">Refund ID</label>
              <select id="refund_id" class="form-control" name="refund_id">
              <option selected>Choose...</option>
              {% for p in refund_ids %}
              <option value="{{ p }}">{{ p }}</option>
              {% endfor %}
              </select>
          </div>        
        </div>
        <div class="form-row">
            <div class="form-group col-12">
                <label for="payment_id">Payment ID</label>
                <select id="payment_id" class="form-control" name="payment_id">
                <option selected>Choose...</option>
                {% for p in payment_ids %}
                <option value="{{ p }}">{{ p }}</option>
                {% endfor %}
                </select>
            </div>        
        </div>
        <a href="{% url 'refunds:allRefundsGUI' %}"><button type="button" class="btn btn-primary" onclick="">Back</button></a>
        <a href="{% url 'refunds:filterRefundsGUI' %}"><button style="float: right; margin-left: 1%;" type="button" class="btn btn-warning">Clear Filters</button></a>
        <button style="float: right;" type="submit" class="btn btn-success">Search</button>
    </form>
      <hr />

      <div class="row">
        <ul>
          {% for refund in refunds %}
            <li>
                <a href="{% url 'refunds:showRefundGUI' refund.refund_id %}">{{ refund }}</a>
            </li>
            <hr />
          {% endfor %}
        </ul>
      </div>

    </main>

</body>

</html>

refunds_app/refunds/templates/refunds/showRefund.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Refund {{ refund_id }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body>
    
    <main role="main" class="container">
        <h3>Refund {{ refund_id }}</h3>
        <hr />

        <ul>
            <li>{{ refund }}</li>
            <li><b>Associated payment:</b> {{ payment }}</li>
        </ul>
        
        <hr />
        <a href="{% url 'refunds:allRefundsGUI' %}"><button class="btn btn-primary" style="float: right;" type="button" >All Refunds</button></a>
    </main>
  </body>